<?php


/**
 * This class adds structure of 'ABPerson' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Mar 14 14:28:43 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AbpersonMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AbpersonMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AbpersonPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AbpersonPeer::TABLE_NAME);
		$tMap->setPhpName('Abperson');
		$tMap->setClassname('Abperson');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ROWID', 'Rowid', 'VARCHAR', true, 255);

		$tMap->addColumn('FIRST', 'First', 'VARCHAR', false, 255);

		$tMap->addColumn('LAST', 'Last', 'VARCHAR', false, 255);

		$tMap->addColumn('MIDDLE', 'Middle', 'VARCHAR', false, 255);

		$tMap->addColumn('FIRSTPHONETIC', 'Firstphonetic', 'VARCHAR', false, 255);

		$tMap->addColumn('MIDDLEPHONETIC', 'Middlephonetic', 'VARCHAR', false, 255);

		$tMap->addColumn('LASTPHONETIC', 'Lastphonetic', 'VARCHAR', false, 255);

		$tMap->addColumn('ORGANIZATION', 'Organization', 'VARCHAR', false, 255);

		$tMap->addColumn('DEPARTMENT', 'Department', 'VARCHAR', false, 255);

		$tMap->addColumn('NOTE', 'Note', 'VARCHAR', false, 255);

		$tMap->addPrimaryKey('KIND', 'Kind', 'VARCHAR', true, 255);

		$tMap->addColumn('BIRTHDAY', 'Birthday', 'VARCHAR', false, 255);

		$tMap->addColumn('JOBTITLE', 'Jobtitle', 'VARCHAR', false, 255);

		$tMap->addColumn('NICKNAME', 'Nickname', 'VARCHAR', false, 255);

		$tMap->addColumn('PREFIX', 'Prefix', 'VARCHAR', false, 255);

		$tMap->addColumn('SUFFIX', 'Suffix', 'VARCHAR', false, 255);

		$tMap->addColumn('FIRSTSORT', 'Firstsort', 'VARCHAR', false, 255);

		$tMap->addColumn('LASTSORT', 'Lastsort', 'VARCHAR', false, 255);

		$tMap->addPrimaryKey('CREATIONDATE', 'Creationdate', 'VARCHAR', true, 255);

		$tMap->addPrimaryKey('MODIFICATIONDATE', 'Modificationdate', 'VARCHAR', true, 255);

		$tMap->addColumn('COMPOSITENAMEFALLBACK', 'Compositenamefallback', 'VARCHAR', false, 255);

		$tMap->addColumn('EXTERNALIDENTIFIER', 'Externalidentifier', 'VARCHAR', false, 255);

		$tMap->addPrimaryKey('STOREID', 'Storeid', 'VARCHAR', true, 255);

		$tMap->addColumn('DISPLAYNAME', 'Displayname', 'VARCHAR', false, 255);

		$tMap->addColumn('FIRSTSORTSECTION', 'Firstsortsection', 'VARCHAR', false, 255);

		$tMap->addColumn('LASTSORTSECTION', 'Lastsortsection', 'VARCHAR', false, 255);

		$tMap->addPrimaryKey('FIRSTSORTLANGUAGEINDEX', 'Firstsortlanguageindex', 'VARCHAR', true, 255);

		$tMap->addPrimaryKey('LASTSORTLANGUAGEINDEX', 'Lastsortlanguageindex', 'VARCHAR', true, 255);

	} // doBuild()

} // AbpersonMapBuilder
