<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/03/22 15:03:31

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'sqlite:/home/esion/workspace/iphoneAddressBook/trunk/data/AddressBook.sqlitedb',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
