dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
#      dsn:        mysql:dbname=iphoneAddressBook;host=localhost
      dsn: 		'sqlite:%SF_DATA_DIR%/AddressBook.sqlitedb'
#      dsn: 		'sqlite:%SF_DATA_DIR%/test.sqlitedb'
#      username:   root
#      password:   
      encoding:   utf8
      persistent: true
      pooling:    true
