<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/03/21 19:57:22
sfConfig::add(array(
  'app_multivaluelabels' => array (
  0 => 'Mobile',
  1 => 'Home',
  2 => 'Homepage',
  3 => 'contact',
  4 => 'Work',
  5 => 'Other',
  6 => 'free',
  7 => 'gsm belge',
  8 => 'Main',
),
));
