<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/03/21 19:57:22
return array(
'personlist' => new sfRoute('/person/list.:sf_format', array (
  'module' => 'person',
  'action' => 'list',
), array (
  'sf_format' => '(?:html|csv)',
), array (
)),
'abperson' => new sfPropelRouteCollection(array (
  'model' => 'Abperson',
  'module' => 'abperson',
  'prefix_path' => 'abperson',
  'column' => 'ROWID',
  'with_wildcard_routes' => true,
  'name' => 'abperson',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'general',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
