<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/03/22 15:03:22
sfConfig::add(array(
  'app_multivaluelabels' => array (
  0 => 'Mobile',
  1 => 'Home',
  2 => 'Homepage',
  3 => 'Work',
  4 => 'Other',
  5 => 'Main',
),
));
